language: python
sudo: enabled
cache:
  directories:
  - $HOME/.cache/pip
  - /tmp/cached/
python:
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
- python -m spacy download en_core_web_md
- python -m spacy link en_core_web_md en
script:
- py.test test_stack.py
